/*
 * Copyright (C) the libgit3 contributors. All rights reserved.
 *
 * This file is part of libgit3, distributed under the GNU GPL v2 with
 * a Linking Exception. For full terms see the included COPYING file.
 */
#ifndef INCLUDE_git_errors_h__
#define INCLUDE_git_errors_h__

#include "common.h"

/**
 * @file git3/errors.h
 * @brief Error handling routines and variables
 * @ingroup Git
 * @{
 */
GIT3_BEGIN_DECL

/** Generic return codes */
typedef enum {
	/**
	 * No error occurred; the call was successful.
	 */
	GIT3_OK              =  0,

	/**
	 * An error occurred; call `git3_error_last` for more information.
	 */
	GIT3_ERROR           = -1,

	GIT3_ENOTFOUND       = -3,   /**< Requested object could not be found. */
	GIT3_EEXISTS         = -4,   /**< Object exists preventing operation. */
	GIT3_EAMBIGUOUS      = -5,   /**< More than one object matches. */
	GIT3_EBUFS           = -6,   /**< Output buffer too short to hold data. */

	/**
	 * GIT3_EUSER is a special error that is never generated by libgit3
	 * code.  You can return it from a callback (e.g to stop an iteration)
	 * to know that it was generated by the callback and not by libgit3.
	 */
	GIT3_EUSER           = -7,

	GIT3_EBAREREPO       = -8,   /**< Operation not allowed on bare repository. */
	GIT3_EUNBORNBRANCH   = -9,   /**< HEAD refers to branch with no commits. */
	GIT3_EUNMERGED       = -10,  /**< Merge in progress prevented operation */
	GIT3_ENONFASTFORWARD = -11,  /**< Reference was not fast-forwardable */
	GIT3_EINVALIDSPEC    = -12,	/**< Name/ref spec was not in a valid format */
	GIT3_ECONFLICT       = -13,	/**< Checkout conflicts prevented operation */
	GIT3_ELOCKED         = -14,	/**< Lock file prevented operation */
	GIT3_EMODIFIED       = -15,	/**< Reference value does not match expected */
	GIT3_EAUTH           = -16,	/**< Authentication error */
	GIT3_ECERTIFICATE    = -17,	/**< Server certificate is invalid */
	GIT3_EAPPLIED        = -18,	/**< Patch/merge has already been applied */
	GIT3_EPEEL           = -19,	/**< The requested peel operation is not possible */
	GIT3_EEOF            = -20,	/**< Unexpected EOF */
	GIT3_EINVALID        = -21,	/**< Invalid operation or input */
	GIT3_EUNCOMMITTED    = -22,	/**< Uncommitted changes in index prevented operation */
	GIT3_EDIRECTORY      = -23,	/**< The operation is not valid for a directory */
	GIT3_EMERGECONFLICT  = -24,	/**< A merge conflict exists and cannot continue */

	GIT3_PASSTHROUGH     = -30,	/**< A user-configured callback refused to act */
	GIT3_ITEROVER        = -31,	/**< Signals end of iteration with iterator */
	GIT3_RETRY           = -32,	/**< Internal only */
	GIT3_EMISMATCH       = -33,	/**< Hashsum mismatch in object */
	GIT3_EINDEXDIRTY     = -34,	/**< Unsaved changes in the index would be overwritten */
	GIT3_EAPPLYFAIL      = -35,	/**< Patch application failed */
	GIT3_EOWNER          = -36,	/**< The object is not owned by the current user */
	GIT3_TIMEOUT         = -37,	/**< The operation timed out */
	GIT3_EUNCHANGED      = -38,	/**< There were no changes */
	GIT3_ENOTSUPPORTED   = -39,	/**< An option is not supported */
	GIT3_EREADONLY       = -40	/**< The subject is read-only */
} git3_error_code;

/**
 * Error classes are the category of error. They reflect the area of the
 * code where an error occurred.
 */
typedef enum {
	GIT3_ERROR_NONE = 0,
	GIT3_ERROR_NOMEMORY,
	GIT3_ERROR_OS,
	GIT3_ERROR_INVALID,
	GIT3_ERROR_REFERENCE,
	GIT3_ERROR_ZLIB,
	GIT3_ERROR_REPOSITORY,
	GIT3_ERROR_CONFIG,
	GIT3_ERROR_REGEX,
	GIT3_ERROR_ODB,
	GIT3_ERROR_INDEX,
	GIT3_ERROR_OBJECT,
	GIT3_ERROR_NET,
	GIT3_ERROR_TAG,
	GIT3_ERROR_TREE,
	GIT3_ERROR_INDEXER,
	GIT3_ERROR_SSL,
	GIT3_ERROR_SUBMODULE,
	GIT3_ERROR_THREAD,
	GIT3_ERROR_STASH,
	GIT3_ERROR_CHECKOUT,
	GIT3_ERROR_FETCHHEAD,
	GIT3_ERROR_MERGE,
	GIT3_ERROR_SSH,
	GIT3_ERROR_FILTER,
	GIT3_ERROR_REVERT,
	GIT3_ERROR_CALLBACK,
	GIT3_ERROR_CHERRYPICK,
	GIT3_ERROR_DESCRIBE,
	GIT3_ERROR_REBASE,
	GIT3_ERROR_FILESYSTEM,
	GIT3_ERROR_PATCH,
	GIT3_ERROR_WORKTREE,
	GIT3_ERROR_SHA,
	GIT3_ERROR_HTTP,
	GIT3_ERROR_INTERNAL,
	GIT3_ERROR_GRAFTS
} git3_error_t;

/**
 * Structure to store extra details of the last error that occurred.
 *
 * This is kept on a per-thread basis if GIT3_THREADS was defined when the
 * library was build, otherwise one is kept globally for the library
 */
typedef struct {
	char *message;  /**< The error message for the last error. */
	int klass;      /**< The category of the last error. @type git3_error_t */
} git3_error;

/**
 * Return the last `git3_error` object that was generated for the
 * current thread.
 *
 * This function will never return NULL.
 *
 * Callers should not rely on this to determine whether an error has
 * occurred. For error checking, callers should examine the return
 * codes of libgit3 functions.
 *
 * This call can only reliably report error messages when an error
 * has occurred. (It may contain stale information if it is called
 * after a different function that succeeds.)
 *
 * The memory for this object is managed by libgit3. It should not
 * be freed.
 *
 * @return A pointer to a `git3_error` object that describes the error.
 */
GIT3_EXTERN(const git3_error *) git3_error_last(void);

/** @} */
GIT3_END_DECL

#endif
