/*
 * Copyright (C) the libgit2 contributors. All rights reserved.
 *
 * This file is part of libgit2, distributed under the GNU GPL v2 with
 * a Linking Exception. For full terms see the included COPYING file.
 */

#ifndef INCLUDE_git_git_h__
#define INCLUDE_git_git_h__

#include "git3/annotated_commit.h"
#include "git3/apply.h"
#include "git3/attr.h"
#include "git3/blob.h"
#include "git3/blame.h"
#include "git3/branch.h"
#include "git3/buffer.h"
#include "git3/cert.h"
#include "git3/checkout.h"
#include "git3/cherrypick.h"
#include "git3/clone.h"
#include "git3/commit.h"
#include "git3/common.h"
#include "git3/config.h"
#include "git3/credential.h"
#include "git3/deprecated.h"
#include "git3/describe.h"
#include "git3/diff.h"
#include "git3/email.h"
#include "git3/errors.h"
#include "git3/experimental.h"
#include "git3/filter.h"
#include "git3/global.h"
#include "git3/graph.h"
#include "git3/ignore.h"
#include "git3/index.h"
#include "git3/indexer.h"
#include "git3/mailmap.h"
#include "git3/merge.h"
#include "git3/message.h"
#include "git3/net.h"
#include "git3/notes.h"
#include "git3/object.h"
#include "git3/odb.h"
#include "git3/odb_backend.h"
#include "git3/oid.h"
#include "git3/pack.h"
#include "git3/patch.h"
#include "git3/pathspec.h"
#include "git3/proxy.h"
#include "git3/rebase.h"
#include "git3/refdb.h"
#include "git3/reflog.h"
#include "git3/refs.h"
#include "git3/refspec.h"
#include "git3/remote.h"
#include "git3/repository.h"
#include "git3/reset.h"
#include "git3/revert.h"
#include "git3/revparse.h"
#include "git3/revwalk.h"
#include "git3/signature.h"
#include "git3/stash.h"
#include "git3/status.h"
#include "git3/submodule.h"
#include "git3/tag.h"
#include "git3/transport.h"
#include "git3/transaction.h"
#include "git3/tree.h"
#include "git3/types.h"
#include "git3/version.h"
#include "git3/worktree.h"

#endif
